let myString="javascript+es+super+cool";
let myArray3=myString.split("+");
let arrayLegth=myArray3.length;
let lastItem=myArray3[arrayLegth -1];
let myInverseArray=myArray3.reverse();
myInverseArray.push("fantastico");
console.log(myArray3);
console.log(arrayLegth);
console.log(lastItem);
console.log(myInverseArray);
